version: '3.8'

services:
  hadoop:
    image: hadoop-debian12
    container_name: hadoop-debian12
    ports:
      - "50070:50070"
      - "8088:8088"
      - "8042:8042"
      - "22:22"
    volumes:
      - hadoop-data:/opt/hadoop/dfs
    networks:
      - hadoopnet
    restart: on-failure
    
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_DB=hive
      - POSTGRES_USER=hiveuser
      - POSTGRES_PASSWORD=hivepassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - hadoopnet

  hive:
    build: ./hive
    container_name: hive
    env_file: ./hive/hive.env  # Reference to the environment file
    depends_on:
      - postgres
    ports:
      - "10000:10000"
      - "10002:10002"
    volumes:
      - hivemetastore:/opt/hive-metastore
    networks:
      - hadoopnet
      
volumes:
  hadoop-data:
  pgdata:
  hivemetastore:

networks:
  hadoopnet:
    driver: bridge